---
title: "Regression Results for TWFE Model"
author: "Joe White"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: false
    number_sections: false
  html_document:
    toc: false
    df_print: paged
fontsize: 11pt
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(scipen = 999, digits = 3)

library(fixest)
library(dplyr)
library(readr)
library(modelsummary)
```

```{r regressions}
# === Load panel ===
panel_fp <- "C:/Repositories/white-bowblis-nhmc/data/clean/pbj_panel_with_chow_dummies.csv"
df <- read_csv(
  panel_fp,
  col_types = cols(
    month = col_date(),
    cms_certification_number = col_character()
  )
)

# === Prep variables ===
df <- df %>%
  mutate(
    for_profit    = as.integer(for_profit),
    non_profit    = as.integer(non_profit),
    is_chain      = as.integer(is_chain),
    ccrc_facility = as.integer(ccrc_facility),
    urban         = as.integer(ifelse(urban %in% c(1, "1"), 1, 0)),
    cm_state_q    = ifelse(is.na(case_mix_quartile_state), -1L, as.integer(case_mix_quartile_state))
  )

# === Models ===
m1 <- feols(
  rn_hppd ~ for_profit + non_profit + is_chain + num_beds + ccrc_facility +
    occupancy_rate + pct_medicare + pct_medicaid +
    i(cm_state_q, ref = -1) + urban | cms_certification_number + month,
  data = df,
  vcov = ~ cms_certification_number + month
)

m2 <- feols(
  lpn_hppd ~ for_profit + non_profit + is_chain + num_beds + ccrc_facility +
    occupancy_rate + pct_medicare + pct_medicaid +
    i(cm_state_q, ref = -1) + urban | cms_certification_number + month,
  data = df,
  vcov = ~ cms_certification_number + month
)

m3 <- feols(
  cna_hppd ~ for_profit + non_profit + is_chain + num_beds + ccrc_facility +
    occupancy_rate + pct_medicare + pct_medicaid +
    i(cm_state_q, ref = -1) + urban | cms_certification_number + month,
  data = df,
  vcov = ~ cms_certification_number + month
)

m4 <- feols(
  total_hppd ~ for_profit + non_profit + is_chain + num_beds + ccrc_facility +
    occupancy_rate + pct_medicare + pct_medicaid +
    i(cm_state_q, ref = -1) + urban | cms_certification_number + month,
  data = df,
  vcov = ~ cms_certification_number + month
)
```

## Summary Table

```{r table, results='asis'}
modelsummary(
  list(
    "RN HPPD"    = m1,
    "LPN HPPD"   = m2,
    "CNA HPPD"   = m3,
    "Total HPPD" = m4
  ),
  stars = TRUE,
  gof_omit = 'IC|Log|Adj|Within|Between|Overall',
  title = 'HPPD Regressions with Facility & Month FE',
  output = "markdown"
)
```

## Raw Summaries

```{r raw-output, echo=TRUE}
summary(m1)
summary(m2)
summary(m3)
summary(m4)
```
